In [1]:
import requests
import matplotlib.pyplot as plt
import json
import pandas as pd

In [2]:
#pip install openpyxl

In [3]:
#from openpyxl import load_workbook
#NSScrisis = load_workbook("../data/NSSCrisisv.1 (1).xlsx")

In [4]:
#NSScrisis

In [5]:
pd.read_excel('../data/NSSCrisisv.1 (1).xlsx')

,FamilyandChildrensService - CallReports export requested on Monday May 9 2022 at 9:57 AM.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 303,Unnamed: 304,Unnamed: 305,Unnamed: 306,Unnamed: 307,Unnamed: 308,Unnamed: 309,Unnamed: 310,Unnamed: 311,Unnamed: 312
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CallReportNum,ReportVersion,LinkedToCallReportNum,CallDateAndTimeStart,CallDateAndTimeEnd,CallLength,CallerNum,PhoneWorkerNum,PhoneWorkerName,WasRealCall,...,SUI AX Third-Party Risk Assessment Demographic...,SUI AX Third-Party Risk Assessment Demographic...,Suicide Assessment - Are you thinking of suicide?,Suicide Assessment - Caller is having thoughts...,Suicide Assessment - Do you own a firearm?,Suicide Assessment - Have you ever attempted t...,Suicide Assessment - Have you thought about su...,Suicide Assessment - Suicide in progress?,Transfer Information - Were you transferred to...,Transfer Information - Which line/agency trans...
2,96627022,Crisis,NaN,2021-12-31 23:35:00,2021-12-31 23:58:00,23,-1,136748,Lisa Crawford,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,96626934,Crisis,NaN,2021-12-31 23:29:00,2021-12-31 23:35:00,6,-1,136748,Lisa Crawford,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,96626654,Crisis,NaN,2021-12-31 23:07:00,2021-12-31 23:28:00,21,1030262,136748,Lisa Crawford,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52873,69492892,Crisis,NaN,2020-01-01 05:14:00,2020-01-01 05:28:00,14,1029822,101461,Rachel Bailey,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52874,69492741,Crisis,NaN,2020-01-01 04:45:00,2020-01-01 05:05:00,20,-1,101461,Rachel Bailey,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52875,69492019,Crisis,NaN,2020-01-01 03:00:00,2020-01-01 03:18:00,18,-1,101461,Rachel Bailey,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52876,69492070,Crisis,NaN,2020-01-01 01:45:00,2020-01-01 01:49:00,4,-1,101461,Rachel Bailey,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52877,69492055,Crisis,NaN,2020-01-01 00:04:00,2020-01-01 00:05:00,1,-1,101461,Rachel Bailey,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
pd.read_excel('../data/NSSCrisisv.1 (1).xlsx', index_col=0, header=0, usecols="A:J", names="")

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
FamilyandChildrensService - CallReports export requested on Monday May 9 2022 at 9:57 AM.,,,,,,
,NaN,NaN,NaN,NaN,NaN,NaN
CallReportNum,ReportVersion,LinkedToCallReportNum,CallDateAndTimeStart,CallDateAndTimeEnd,CallLength,CallerNum
96627022,Crisis,NaN,2021-12-31 23:35:00,2021-12-31 23:58:00,23,-1
96626934,Crisis,NaN,2021-12-31 23:29:00,2021-12-31 23:35:00,6,-1
96626654,Crisis,NaN,2021-12-31 23:07:00,2021-12-31 23:28:00,21,1030262
...,...,...,...,...,...,...
69492892,Crisis,NaN,2020-01-01 05:14:00,2020-01-01 05:28:00,14,1029822
69492741,Crisis,NaN,2020-01-01 04:45:00,2020-01-01 05:05:00,20,-1
69492019,Crisis,NaN,2020-01-01 03:00:00,2020-01-01 03:18:00,18,-1
69492070,Crisis,NaN,2020-01-01 01:45:00,2020-01-01 01:49:00,4,-1
69492055,Crisis,NaN,2020-01-01 00:04:00,2020-01-01 00:05:00,1,-1

In [7]:
pd.read_excel('../data/NSSCrisisv.2.xlsx')

,FamilyandChildrensService - CallReports export requested on Monday May 9 2022 at 9:58 AM.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255,Unnamed: 256,Unnamed: 257,Unnamed: 258,Unnamed: 259,Unnamed: 260
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CallReportNum,ReportVersion,LinkedToCallReportNum,CallDateAndTimeStart,CallDateAndTimeEnd,CallLength,CallerNum,PhoneWorkerNum,PhoneWorkerName,WasRealCall,...,SUI AX Phone Line - SAMHSA - Was the offer for...,SUI AX Reassessment - Change in Risk Level,SUI AX Reassessment - Initial Suicide Risk Ass...,SUI AX Reassessment - Is this a Reassessment?,SUI AX Reassessment - Suicide Risk Re-assessment,SUI AX Third-Party Risk Assessment Demographic...,SUI AX Third-Party Risk Assessment Demographic...,Suicide Imminent Risk - Third party suicide ca...,Suicide Imminent Risk - Was emergency rescue d...,Suicide Imminent Risk - Was suicidal ideation ...
2,101384892,Crisis v.2,NaN,2022-04-30 23:19:00,2022-04-30 23:27:00,8,1025380,55599,Darren Anderson,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,101384348,Crisis v.2,NaN,2022-04-30 22:46:00,2022-04-30 23:13:00,27,-1,55599,Darren Anderson,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,101383635,Crisis v.2,NaN,2022-04-30 22:03:00,2022-04-30 22:27:00,24,-1,169061,Tandra Freeman,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10645,96673255,Homicidal Risk Assessment,Yes,2022-01-01 20:34:00,2022-01-01 20:58:00,24,-1,166157,Tasia Thompson,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10646,96645142,Suicide Risk Assessment,Yes,2022-01-01 18:27:00,2022-01-01 19:12:00,45,-1,166157,Tasia Thompson,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10647,96640741,Suicide Risk Assessment,Yes,2022-01-01 14:44:00,2022-01-01 15:19:00,35,-1,136748,Lisa Crawford,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10648,96849680,Crisis v.2,NaN,2022-01-01 12:09:00,2022-01-01 12:10:00,1,-1,53133,Shannon Huffman,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10649,97267704,Suicide Risk Assessment,Yes,2022-01-01 02:30:00,2022-01-01 03:10:00,40,-1,169061,Tandra Freeman,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
pd.read_excel('../data/NSSCrisisv.2.xlsx', index_col=0, header=0, usecols="A:G")

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
FamilyandChildrensService - CallReports export requested on Monday May 9 2022 at 9:58 AM.,,,,,,
,NaN,NaN,NaN,NaN,NaN,NaN
CallReportNum,ReportVersion,LinkedToCallReportNum,CallDateAndTimeStart,CallDateAndTimeEnd,CallLength,CallerNum
101384892,Crisis v.2,NaN,2022-04-30 23:19:00,2022-04-30 23:27:00,8,1025380
101384348,Crisis v.2,NaN,2022-04-30 22:46:00,2022-04-30 23:13:00,27,-1
101383635,Crisis v.2,NaN,2022-04-30 22:03:00,2022-04-30 22:27:00,24,-1
...,...,...,...,...,...,...
96673255,Homicidal Risk Assessment,Yes,2022-01-01 20:34:00,2022-01-01 20:58:00,24,-1
96645142,Suicide Risk Assessment,Yes,2022-01-01 18:27:00,2022-01-01 19:12:00,45,-1
96640741,Suicide Risk Assessment,Yes,2022-01-01 14:44:00,2022-01-01 15:19:00,35,-1
96849680,Crisis v.2,NaN,2022-01-01 12:09:00,2022-01-01 12:10:00,1,-1
97267704,Suicide Risk Assessment,Yes,2022-01-01 02:30:00,2022-01-01 03:10:00,40,-1

In [9]:
crisis = pd.concat(['NSScrisis.2', 'NSScrisis.1'])

TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid

In [10]:
contact1 = pd.read_csv('../data/Contact center call volume_2020-2022.xlsx - 2020.csv')

In [11]:
contact1

,Report Info,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Queue:,"AWARE,Community Response,Crisis Eng,Crisis Eng...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,"Crisis Spanish,Crisis Spanish PRIORITY,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,"Lifeline,MHART,Pet Loss,REDLINE,Referral Line,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SAMHSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Start Date:,1/1/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
99,Within 90 secs,11637 calls,524,71.34%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,Within 105 secs,12062 calls,425,73.94%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,Within 120 secs,12403 calls,341,76.03%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,Within 135 secs,12981 calls,578,79.57%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,Within 150+ secs,16313 calls,3332,100.00%,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
contact2 = pd.read_csv('../data/Contact center call volume_2020-2022.xlsx - 2021.csv')

In [13]:
contact2

,Report Info,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Queue:,"AWARE,Community Response,Crisis Eng,Crisis Eng...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,"Crisis Spanish,Crisis Spanish PRIORITY,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,"Lifeline,MHART,Pet Loss,REDLINE,Referral Line,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,SAMHSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Start Date:,1/1/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
112,Within 90 secs,9823 calls,656,61.18%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,Within 105 secs,10303 calls,480,64.17%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,Within 120 secs,10741 calls,438,66.90%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,Within 135 secs,11422 calls,681,71.14%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,Within 150+ secs,16056 calls,4634,100.00%,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
contact3 = pd.read_csv('../data/Contact center call volume_2020-2022.xlsx - 2022.csv')

In [15]:
contact3

,Unnamed: 0,"Lifeline,MHART,Pet Loss,REDLINE,Referral Line,",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,SAMHSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Start Date:,1/1/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,End Date:,4/30/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Hour range:,00:00 - 23:59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Period:,120 days,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
99,Within 90 secs,2340 calls,186,60.84%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,Within 105 secs,2487 calls,147,64.66%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,Within 120 secs,2596 calls,109,67.50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,Within 135 secs,2767 calls,171,71.94%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,Within 150+ secs,3846 calls,1079,100.00%,NaN,NaN,NaN,NaN,NaN,NaN,NaN